fragment Children on Topic {
  name id text tags childTopics { name } 
}

query getUser($name: String!) {
  getUser(name: $name){
    name
    rootTopics {name id text tags childTopics{ ...Children } }
  }
}