version: '3.8'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    # needed because the postgres container does not provide a healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./schema:/shared/schema
  auth-service:
    image: docker.pkg.github.com/romitagl/kgraph/backend-hasura-auth:latest
    ports:
    - "3000:3000"
    restart: always
    # shared secrets
    env_file: ./env.local
    environment:
      HASURA_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
  graphql-engine:
    # auto apply migration at the start
    image: docker.pkg.github.com/romitagl/kgraph/backend-hasura-schema:latest
    ports:
    - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
    restart: always
    # shared secrets
    env_file: ./env.local
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
  frontend:
    image: docker.pkg.github.com/romitagl/kgraph/frontend-vue:latest
    ports:
    - "80:80"
    restart: always
    depends_on:
    - "graphql-engine"
volumes:
  postgres_data: {}