mutation addTopicForUser($topicsName: String!, $parent_id: uuid, $content: String, $tags: String) {
  insert_kgraph_topics(objects: {name: $topicsName, parent_id: $parent_id, content: $content, tags: $tags}) {
    returning {
      created_at id
    }
  }
}
