mutation deleteTopicForUser($topicID: uuid!, $username: String!) {
  delete_kgraph_topics(where: {users_username: {_eq: $username}, id: {_eq: $topicID}}) {
    affected_rows
  }
  update_kgraph_topics(where: {parent_id: {_eq: $topicID}}, _set: {parent_id: null}) {
    affected_rows
  }
}