# https://hasura.io/docs/1.0/graphql/core/queries/query-filters.html#text-search-or-pattern-matching-operators-like-similar-etc
query searchTopicsForUser ($topicsName: String! $username: String!) {
  kgraph_topics(where: {users_username: {_eq: $username}, _or: [{name: {_ilike:  $topicsName}}, { content: {_ilike:  $topicsName}}]}) {
    id
    name
    content
    parent_id
    topics_labels {
      label {
        title
      }
    }
  }
}
