mutation updateTopicForUser($topicName: String!, $username: String!, $id: uuid, $content: String) {
  update_kgraph_topics(where: {users_username: {_eq: $username}, id: {_eq: $id}}, _set: {content: $content, name: $topicName}) {
    returning {
      updated_at
    }
  }
}