name: CD Release Pages Demo

on:
  release:
    types: [published]
  # test branch
  push:
    branches:
      - gl/vue
    paths-ignore:
      # skip CI for documentation updates
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2.3.1
        with:
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          # ref: release
          ref: gl/vue
          # Fetch all history for all tags and branches
          fetch-depth: 0

      - name: Install and Build with Demo mode
        shell: bash
        run: |
          # compiles and minifies for production
          # https://cli.vuejs.org/guide/mode-and-env.html#modes
          cd frontend/vue
          npm install
          npm run build -- --mode demo
          cd dist
          git init
          # omit --global to set the identity only in this repository
          git config --global user.email "romitagl@gmail.com"
          git config --global user.name "Gian Luigi Romita"
          git add -A
          git commit -m 'deploy'
          git push -f git@github.com:romitagl/kgraph.git main:gh-pages

      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.4
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: frontend/vue/build # The folder the action should deploy.

      # https://cli.vuejs.org/guide/deployment.html#github-pages

