name: CI

on:
  issue_comment:
    types: [ created ]
  # pull_request_review_comment:
  #   types: [ created, edited ]
  workflow_run:
    workflows: ['Lint Code Base']
    branches:
      - master
    types:
      - completed
    paths-ignore:
      # skip CI for documentation updates
      - "**/*.md"
  push:
    branches:
      - master
      - gl/vue
    paths-ignore:
      # skip CI for documentation updates
      - "**/*.md"

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    # if: (github.event.workflow_run.conclusion == 'success' && github.event_name != 'issue_comment' )|| ((github.event_name == 'pull_request_review_comment' || contains(github.event.comment.html_url, '/pull/')) && contains(github.event.comment.body, '/run-ci'))
    env:
      HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.CI_HASURA_GRAPHQL_ADMIN_SECRET }}
      HASURA_GRAPHQL_JWT_SECRET_KEY: ${{ secrets.CI_HASURA_GRAPHQL_JWT_SECRET }}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_JWT_SECRET_TYPE: "HS256"
      HASURA_GRAPHQL_JWT_SECRET: "{ \"type\": \"${HASURA_GRAPHQL_JWT_SECRET_TYPE}\", \"key\": \"${HASURA_GRAPHQL_JWT_SECRET_KEY}\" }"

    steps:
      - name: Clone Repo - PR
        if: github.event_name == 'issue_comment'
        uses: actions/checkout@v2
        with:
          ref: ${{format('refs/pull/{0}/head', github.event.issue.number )}}
          # ref: refs/heads/${{ github.head_ref }} # Or: ${{ github.event.pull_request.head.ref }}

      - name: Clone Repo - Master
        if: github.event_name != 'issue_comment'
        uses: actions/checkout@v2

      - name: Run CI Tests
        shell: bash
        run: |
          make ci