name: CI

on:
  pull_request_review_comment:
    types: [ created, edited ]
  workflow_run:
    workflows: ['Lint Code Base']
    branches:
      - master
    types:
      - completed
    paths-ignore:
      # skip CI for documentation updates
      - "**/*.md"
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     # skip CI for documentation updates
  #     - "**/*.md"

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/run-ci'))
    env:
      HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.CI_HASURA_GRAPHQL_ADMIN_SECRET }}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Run CI Tests
        shell: bash
        run: |
          make ci